
strategy:
  matrix:
    ubuntu:
      imageName: 'ubuntu-latest'
    macos:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

trigger:
- master

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    architecture: 'x64'

- script: python -m pip install -U tox 
  displayName: 'Install dependencies'

- script: tox -p all
  displayName: 'Run tests'
