
trigger:
- master

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: python -m pip install -U tox 
  displayName: 'Install dependencies'

- script: tox -p all -e py37-i106,py37-c10
  displayName: 'Run tests'
