trigger:
- master

variables:
  major: 0
  minor: 2

name: $(major).$(minor)$(Rev:.r)

jobs:

- job: Test
  strategy:
    maxParallel: 5
    matrix:
      Ubuntu-py3.7:
        imageName: 'ubuntu-latest'
        python.version: '3.7'
        python.env: '37'
      Ubuntu-py3.8:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
        python.env: '38'
      macOS-py3.7:
        imageName: 'macos-latest'
        python.version: '3.7'
        python.env: '37'
      macOS-py3.8:
        imageName: 'macos-latest'
        python.version: '3.8'
        python.env: '38'
      Windows-py3.7:
        imageName: 'windows-latest'
        python.version: '3.7'
        python.env: '37'
      Windows-py3.8:
        imageName: 'windows-latest'
        python.version: '3.8'
        python.env: '38'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
      architecture: 'x64'

  - script: python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: "pytest tests --cov c10_tools --cov-report xml --cov-report html --cov-append"
    displayName: 'Run Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit-*.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

# Create dist files for PyPI release
- job: Build
  dependsOn: 'Test'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      architecture: 'x64'

  - script: "python -m pip install -U pip setuptools wheel"
    displayName: "Install dependencies"

  - script: "echo \"version = '$(Build.BuildNumber)'\" > c10_tools/version.py"
    displayName: "Update version # to match build"

  - script: "python setup.py sdist bdist_wheel"
    displayName: "Build source & wheel distributions"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: dist

# Bundle "full" zip that includes dependencies for offline installation.
- job: Package
  dependsOn: 'Test'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      architecture: 'x64'

  - script: "python -m pip download . -r requirements.txt -d dependencies --no-binary :all:"
    displayName: 'Download dependencies'

  - script: "python -m pip download cbitstruct -d dependencies --no-binary :all:"
    displayName: 'Download cbitstruct'

  - task: ArchiveFiles@2
    displayName: 'Zip full package'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)' 
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'c10-tools-$(Build.BuildNumber)-full.zip' 
      replaceExistingArchive: true 

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'c10-tools-$(Build.BuildNumber)-full.zip'
      artifactName: complete-library

# Bundle native binaries for windows.
- job: Build_Native
  dependsOn: 'Test'
  strategy:
    maxParallel: 2
    matrix:
      linux:
        imageName: 'ubuntu-latest'
        platform: 'linux'
      windows:
        imageName: 'windows-latest'
        platform: 'windows'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      architecture: 'x64'

  - script: "python -m pip install . -r requirements.txt"
    displayName: 'Install dependencies'

  - script: "python setup.py build_scripts"
    displayName: 'Build'

  - task: ArchiveFiles@2
    displayName: 'Zip binaries'
    inputs:
      rootFolderOrFile: 'dist' 
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'c10-tools-$(Build.BuildNumber)-$(platform).zip' 
      replaceExistingArchive: true 

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'c10-tools-$(Build.BuildNumber)-$(platform).zip' 
      artifactName: native-binaries
