trigger:
- master

name: 1.1.0

jobs:

- job: Test
  strategy:
    maxParallel: 5
    matrix:
      Ubuntu-py3.7:
        imageName: 'ubuntu-latest'
        python.version: '3.7'
        python.env: '37'
      Ubuntu-py3.8:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
        python.env: '38'
      Ubuntu-py3.9:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
        python.env: '39'
      macOS-py3.7:
        imageName: 'macos-latest'
        python.version: '3.7'
        python.env: '37'
      macOS-py3.8:
        imageName: 'macos-latest'
        python.version: '3.8'
        python.env: '38'
      macOS-py3.9:
        imageName: 'macos-latest'
        python.version: '3.9'
        python.env: '39'
      Windows-py3.7:
        imageName: 'windows-latest'
        python.version: '3.7'
        python.env: '37'
      Windows-py3.8:
        imageName: 'windows-latest'
        python.version: '3.8'
        python.env: '38'
      Windows-py3.9:
        imageName: 'windows-latest'
        python.version: '3.9'
        python.env: '39'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
      architecture: 'x64'

  - script: python -m pip install -U pip pdm
    displayName: 'Install pdm'

  - script: pdm install -d -G :all
    displayName: 'Install dependencies'

  - script: "pdm run pytest --junitxml=junit-$(python.version).xml --cov c10_tools --cov-report xml --cov-report html --cov-append"
    displayName: 'Run Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit-*.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

# Create dist files for PyPI release
- job: Build
  dependsOn: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      architecture: 'x64'

  - script: python -m pip install -U pip pdm
    displayName: 'Install pdm'

  - script: pdm install -d -G :all
    displayName: 'Install dependencies'

  - script: "pdm build"
    displayName: "Build source & wheel distributions"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: dist

# Bundle "full" zip that includes dependencies for offline installation.
- job: Package
  dependsOn: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      architecture: 'x64'

  - script: "python -m pip download . -d dependencies --no-binary :all:"
    displayName: 'Download dependencies'

  - script: "python -m pip download cbitstruct -d dependencies --no-binary :all:"
    displayName: 'Download cbitstruct'

  - task: ArchiveFiles@2
    displayName: 'Zip full package'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'c10-tools-$(Build.BuildNumber)-full.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'c10-tools-$(Build.BuildNumber)-full.zip'
      artifactName: complete-library